


#ifndef _REMOTEMEDATASTRUCTURES_h
#define _REMOTEMEDATASTRUCTURES_h


enum WSUserMessageSettings { NO_RENEWAL=0, RENEWAL_IF_FAILED=1};

enum MessageType { USER_MESSAGE = 100, USER_MESSAGE_DELIVER_STATUS = 101, REGISTER_DEVICE = 200, REGISTER_CHILD_DEVICE = 201, ADD_DATA = 300 };

#endif